### ISSUE TITLE
Panics while discovery

### ISSUE THREAD

**Issue by JekaMas** [kowala-tech/kcoin#430]
### _Type_:
Issue

### _What happened? / What do you need?_:
```
INFO [06-25|13:20:24] There's a majority in the pre-commit sub-election! 
INFO [06-25|13:20:24] Commit state 
INFO [06-25|13:20:24] Starting a new election 
fatal error: concurrent map writes

goroutine 80 [running]:
runtime.throw(0xf71325, 0x15)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420e51dd8 sp=0xc420e51db8 pc=0x431965
runtime.mapdelete_fast64(0xe015e0, 0xc420d33920, 0xc420d66700)
	/usr/local/go/src/runtime/hashmap_fast.go:796 +0x1f7 fp=0xc420e51e20 sp=0xc420e51dd8 pc=0x412fc7
github.com/kowala-tech/kcoin/client/p2p/discv5.(*ticketStore).removeTicketRef(0xc4200ea2a0, 0xc4201e8a10, 0x0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/ticket.go:436 +0x40c fp=0xc420e51ef0 sp=0xc420e51e20 pc=0xa491bc
github.com/kowala-tech/kcoin/client/p2p/discv5.(*ticketStore).ticketRegistered(0xc4200ea2a0, 0xc4201e8a10, 0x0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/ticket.go:350 +0x14c fp=0xc420e51f58 sp=0xc420e51ef0 pc=0xa489cc
github.com/kowala-tech/kcoin/client/p2p/discv5.(*Network).loop.func3(0xc4201645a0, 0xc420d46000, 0xc420198300)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/net.go:401 +0xb2 fp=0xc420e51fc8 sp=0xc420e51f58 pc=0xa52612
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420e51fd0 sp=0xc420e51fc8 pc=0x462f51
created by github.com/kowala-tech/kcoin/client/p2p/discv5.(*Network).loop
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/net.go:395 +0x2c9

goroutine 1 [chan receive]:
github.com/kowala-tech/kcoin/client/node.(*Node).Wait(0xc42008a6c0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/node/node.go:517 +0x7f
main.kowala(0xc4200a6000, 0x5, 0xf48218)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/cmd/kcoin/main.go:212 +0x51
github.com/kowala-tech/kcoin/client/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xdca400, 0x10108b8, 0xc4200a6000, 0xc4200a6000, 0xc4204adf40)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/kowala-tech/kcoin/client/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42006a340, 0xc420010140, 0x13, 0x14, 0x0, 0x0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x635
main.main()
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/cmd/kcoin/main.go:200 +0x55

goroutine 6 [chan receive]:
github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc420012540, 0xc420012480)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x18f
created by github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x149

goroutine 7 [chan receive]:
github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc420012540, 0xc4200124e0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x8b
created by github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x178

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 51 [select]:
github.com/kowala-tech/kcoin/client/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc4201b8000)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x172
created by github.com/kowala-tech/kcoin/client/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x195

goroutine 22 [select]:
github.com/kowala-tech/kcoin/client/accounts/keystore.(*watcher).loop(0xc42023d940)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/accounts/keystore/watch.go:94 +0x511
created by github.com/kowala-tech/kcoin/client/accounts/keystore.(*watcher).start
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/accounts/keystore/watch.go:52 +0x5d
```

### _If it's an issue, how can we reproduce it?_:
Run e2e tests a few times.

### _Priority_:
Medium

**Comment by acroca** [comment]
In case it helps, I got the following:
```
panic: nil

goroutine 31 [running]:
github.com/kowala-tech/kcoin/client/p2p/discv5.(*ticketStore).removeTicketRef(0xc4201c1500, 0xc424b3f960, 0x0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/ticket.go:425 +0x4bb
github.com/kowala-tech/kcoin/client/p2p/discv5.(*ticketStore).ticketRegistered(0xc4201c1500, 0xc424b3f960, 0x0)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/ticket.go:350 +0x14c
github.com/kowala-tech/kcoin/client/p2p/discv5.(*Network).loop.func3(0xc4224ffe00, 0xc4200a60f0, 0xc420030700)
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/net.go:401 +0x9e
created by github.com/kowala-tech/kcoin/client/p2p/discv5.(*Network).loop
	/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/discv5/net.go:395 +0x29a
```

**Comment by yourheropaul** [comment]
This is causing one of the issues, and happening quite often on the testnet (which is causing it to die):

```	
if idx == -1 {
	panic(nil)
}
```

(https://github.com/kowala-tech/kcoin/blob/dev/client/p2p/discv5/ticket.go#L425)

Does that really need to cause a panic?
