### ISSUE TITLE
Exception running a new validator

### ISSUE THREAD

**Issue by acroca** [kowala-tech/kcoin#496]
I've got this error while running a new validator:
```
WARN [07-06|13:56:07] Joining the network 2 with a deposit 5000000000000000000. Account "0xFc4e2a1b223285CEd807180956A1792a83161d2A" 
INFO [07-06|13:56:07] Submitted transaction                    fullhash=0x4a1bd384edc85b4212d6b176b04bede4051fccd24607e170ddbfb3159ecb4f24 recipient=0x6f04441A6eD440Cc139a4E33402b438C27E97F4B
INFO [07-06|13:56:07] Waiting confirmation to participate in the consensus 
INFO [07-06|13:56:08] Imported new chain segment               blocks=1 txs=1 mgas=0.199 elapsed=1.678ms   mgasps=118.684 number=19 hash=4dc604…5b542d
INFO [07-06|13:56:08] Starting validation operation 
INFO [07-06|13:56:08] Voter has been accepted in the election 
INFO [07-06|13:56:08] Starting a new election 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7e3726]

goroutine 129 [running]:
github.com/kowala-tech/kcoin/client/core/types.(*DataSet).Add(0x0, 0xc421932880)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/core/types/chunk.go:123 +0x26
github.com/kowala-tech/kcoin/client/knode/validator.(*validator).AddBlockFragment(0xc42025ca80, 0xc421931060, 0x0, 0xc421932880, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/validator/validator.go:580 +0x90
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handleMsg(0xc4201d24b0, 0xc420dc0630, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:648 +0x81a
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handle(0xc4201d24b0, 0xc420dc0630, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:279 +0x6cb
github.com/kowala-tech/kcoin/client/knode.NewProtocolManager.func1(0xc420d75440, 0x192ee40, 0xc420232310, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:123 +0x1f2
github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols.func1(0xc420232310, 0xc420d75440, 0x192ee40, 0xc420232310)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:332 +0x66
created by github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:331 +0x228
```

/cc @rgeraldes

**Comment by acroca** [comment]
[logs_err.zip](https://github.com/kowala-tech/kcoin/files/2170851/logs_err.zip)
Here all logs. They are from a different run.

**Comment by acroca** [comment]
@rgeraldes it still happens, it's the reason of the random e2e failures in the CI.
```
WARN [07-12|09:12:00.877] Joining the network 2 with a deposit 5000000000000000000. Account "0xF164Bc8605F1217b0AfF2bA0E7241Aa1FA6ad649" 
INFO [07-12|09:12:00.913] Submitted transaction                    fullhash=0xec412adfa1030de39f2d4edb389839f30752cafbe11f78f937c70a536cc00a94 recipient=0x6f04441A6eD440Cc139a4E33402b438C27E97F4B
INFO [07-12|09:12:00.919] Waiting confirmation to participate in the consensus 
INFO [07-12|09:12:01.028] Imported new chain segment               blocks=1  txs=1 mgas=0.199 elapsed=1.549ms  mgasps=128.599 number=19 hash=9f1e6c…78ebd0 cache=43.00kB
INFO [07-12|09:12:01.028] Starting validation operation 
INFO [07-12|09:12:01.028] Voter has been accepted in the election 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb89220]

goroutine 140 [running]:
github.com/kowala-tech/kcoin/client/knode/validator.(*VotingSystem).getVoteSet(...)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/validator/consensus.go:119
github.com/kowala-tech/kcoin/client/knode/validator.(*VotingSystem).Add(0x0, 0x1aa3140, 0xc421471360, 0xc421471360, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/validator/consensus.go:103 +0xb0
github.com/kowala-tech/kcoin/client/knode/validator.(*validator).AddVote(0xc420265500, 0xc421502900, 0x1a9c980, 0xc42151d5c0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/validator/validator.go:303 +0xa5
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handleMsg(0xc42035e620, 0xc42028d130, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:643 +0xb79
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handle(0xc42035e620, 0xc42028d130, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:283 +0x744
github.com/kowala-tech/kcoin/client/knode.NewProtocolManager.func1(0xc420d8dbc0, 0x1aa3540, 0xc420234310, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:120 +0x1f2
github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols.func1(0xc420234310, 0xc420d8dbc0, 0x1aa3540, 0xc420234310)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:336 +0x66
created by github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:335 +0x228
```

**Comment by acroca** [comment]
Still failing in current `dev`

**Comment by acroca** [comment]
[logs.zip](https://github.com/kowala-tech/kcoin/files/2192321/logs.zip)
Attached logs of the latest run containing this error

**Comment by acroca** [comment]
Again: [logs.zip](https://github.com/kowala-tech/kcoin/files/2192381/logs.zip)

**Comment by JekaMas** [comment]
Validator's code is not thread-safe and if can happens that `init` and `AddVote` (or some other method) are called in the same time.
This happens because `client/knode/handler.go` `ProtocolManager.handle(p *peer)` is running for each peer in a goroutine.

So we need to refactor all `knode/validator/validator.go`, `knode/validator/consensus.go` to make it possible to use them in a thread-safe way.

@acroca @yourheropaul @rgeraldes
