### ISSUE TITLE
Fix validation errors

### ISSUE THREAD

**Issue by JekaMas** [kowala-tech/kcoin#612]
### _Type_:
Issue

### _What happened? / What do you need?_:
Validator tests often fail with errors:
```
  Scenario: Re-Start mining
    Given I have the following accounts:
      Error: timeout error: node is synchronised
```

```
--- Failed steps:

  Scenario: Re-Start mining
    And I wait for my node to be synced
      Error: timeout error: timeout waiting for node sync
```

### _If it's an issue, how can we reproduce it?_:
Run validator tests many times

### _Priority_:
Medium

**Comment by acroca** [comment]
One more:
```
--- Failed steps:

  Scenario: Mining rewards: basic
    And I start validator with 5 mTokens deposit
      Error: error while executing '[./kcoin attach /root/.kcoin/kusd/kcoin.ipc --exec eth.blockNumber]': "Error response from daemon: Container 65a3620c1dc7b87037d94b0533f430b9eeb2d32c7daf9578d5374b0d0baa82c1 is not running"
```

relevant log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x88c3c6]

goroutine 162 [running]:
github.com/kowala-tech/kcoin/client/core/types.(*DataSet).Add(0x0, 0xc421924680)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/core/types/chunk.go:123 +0x26
github.com/kowala-tech/kcoin/client/knode/validator.(*validator).AddBlockFragment(0xc420207500, 0xc4219514c0, 0x0, 0xc421924680, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/validator/validator.go:589 +0x90
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handleMsg(0xc42036c620, 0xc4200968f0, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:660 +0x825
github.com/kowala-tech/kcoin/client/knode.(*ProtocolManager).handle(0xc42036c620, 0xc4200968f0, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:284 +0x744
github.com/kowala-tech/kcoin/client/knode.NewProtocolManager.func1(0xc420e344e0, 0x1b12720, 0xc4203a5ab0, 0x0, 0x0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/knode/handler.go:121 +0x1f2
github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols.func1(0xc4203a5ab0, 0xc420e344e0, 0x1b12720, 0xc4203a5ab0)
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:336 +0x66
created by github.com/kowala-tech/kcoin/client/p2p.(*Peer).startProtocols
	/go/src/github.com/kowala-tech/kcoin/client/build/_workspace/src/github.com/kowala-tech/kcoin/client/p2p/peer.go:335 +0x228
```
