### ISSUE TITLE
validator.setDeposit() method is missing; no way to set deposit 

### ISSUE THREAD

**Issue by johnreitano** [kowala-tech/kcoin#769]
### _Type_:
Issue

### _What happened? / What do you need?_:
Ran validator.setDeposit(...) as in https://docs.kowala.tech/getting-started/consensus/

### _If it's a request, what do you need it for?_:
To let our exchange partner GMM run mining on testnet.

### _If it's an issue, how can we reproduce it?_:
run validator.setDeposit(validator.getMinimumDeposit())

### _Priority_:
Medium

  * High = We should stop anything we are doing and do this.
If you're writing this calmly, you should probably choose another option.
If it's really that urgent, please make sure we read this.
  * Medium = It's important that we do this within a few days.
  * Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by rgeraldes** [comment]
We no longer use setDeposit - the deposit is now set upon the validator start.
> validator.start(deposit)

**Comment by johnreitano** [comment]
When I call validator.start(x), I get an error message:

```
> validator.setCoinbase(kcoin.accounts[0])
true
>  x = mtoken.getBalance(kcoin.accounts[0]);
1.000002e+24
> validator.start(x);
Error: invalid argument 0: math/big: cannot unmarshal "\"1.000002e+24\"" into a *big.Int
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```

What the correct way to call validator.start()?
